Add yml linter
+fix ini linter.

We can't use `find -exec bash -c ""` because the return code of
bash command will not be the return code of find.

We need to use yamllint one file at a time because the log of
Github Actions drop the name of the yaml file with problem :

Error: [new-lines] wrong new line character: expected \r\n